### ISSUE TITLE
Feature: Auto creation

### ISSUE THREAD

**Issue by nsjames** [GetScatter/CreateBridge#2]
For accounts self-funding from exchanges it would be great if we could add a last parameter option to the memo with a requested `name` for automatic creation which will just assert if name is taken. This will allow us to completely take out back-end steps and fuel creation in one fell swoop from exchanges.

**Comment by surabhil** [comment]
Code for this is present in this PR which is merged to v2 now:
https://github.com/GetScatter/CreateBridge/pull/5
