### ISSUE TITLE
wrong memo, how to refund

### ISSUE THREAD

**Issue by pynixwang** [GetScatter/CreateBridge#7]
create failed.

**Comment by nsjames** [comment]
Can you send some more info like a transaction ID?

**Comment by pynixwang** [comment]
@nsjames https://bloks.io/transaction/d127231abc8bffedd2a2e9fc8fb43d156131370647b1444669308f69d2e2133d

**Comment by pynixwang** [comment]
I transfer from an exchange and forgot to use my public key as memo.

because this exchange call memo as `address tag`, I think it is a simple tag.
